---
- hosts: kubernetes
  tasks:

    - name: Create deployment directory
      file:
        path: /home/ansadm/k8manifests
        state: directory
        mode: '0755'

    - name: Copy application manifest
      copy:
        src: "{{ lookup('env', 'WORKSPACE') }}/k8manifests/deployment.yaml"
        dest: /home/ansadm/k8manifests/deployment.yaml

    - name: Copy service manifest
      copy:
        src: "{{ lookup('env', 'WORKSPACE') }}/k8manifests/service.yaml"
        dest: /home/ansadm/k8manifests/service.yaml
        
    - name: Copy service manifest
      copy:
        src: "{{ lookup('env', 'WORKSPACE') }}/k8manifests/secret.yaml"
        dest: /home/ansadm/k8manifests/secret.yaml

    - name: Apply Kubernetes secret
      ansible.builtin.command:
        cmd: sudo kubectl apply -f secret.yaml
        chdir: /home/ansadm/k8manifests

    - name: Apply Kubernetes deployment
      ansible.builtin.command:
        cmd: sudo kubectl apply -f deployment.yaml
        chdir: /home/ansadm/k8manifests

    - name: Apply Kubernetes service
      ansible.builtin.command:
        cmd: sudo kubectl apply -f service.yaml
        chdir: /home/ansadm/k8manifests
