---
- hosts: k8bootstrap
  tasks:

    - name: Create deployment directory
      file:
        path: /home/ansadm/kubernetes
        state: directory
        mode: '0755'

    - name: Copy application manifest
      copy:
        src: "{{ lookup('env', 'WORKSPACE') }}/kubernetes/application.yaml"
        dest: /home/ansadm/kubernetes/application.yaml

    - name: Copy service manifest
      copy:
        src: "{{ lookup('env', 'WORKSPACE') }}/kubernetes/service.yaml"
        dest: /home/ansadm/kubernetes/service.yaml
